version: '3.7'
services:
  blast:
    image: mosuka/blast:v0.3.2
    environment:
      BLAST_BIND_ADDR: search:10000
      BLAST_GRPC_ADDR: search:10001
      BLAST_HTTP_ADDR: search:10002
      BLAST_RAFT_NODE_ID: node1
      BLAST_RAFT_DIR: /search/node1/raft
      BLAST_STORE_DIR: /search/node1/store
      BLAST_INDEX_DIR: /search/node1/index
      BLAST_INDEX_MAPPING: /search/index_mapping.json
    volumes:
      - ./search:/search
    command: start
  watcher:
    build:
      context: .
      target: blast
    links:
      - blast:blast